service: chasqui



provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Effect: Allow
      Action:
      - s3:*
      Resource: 'arn:aws:s3:::*'

  environment:
      SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}


# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-kms-secrets

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

functions:
  topic_create:
    handler: src/api_handler.topic_create
    description: Creates a new topic
    events:
      - http:
         path: topic/{id}
         method: post

  topic_get:
    handler: src/api_handler.topic_get
    description: Retrieves a given topic
    events:
      - http:
          path: topic/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  topic_delete:
    handler: src/api_handler.topic_delete
    description: Deletes a topic
    events:
      - http:
         path: topic/{id}
         method: delete
         request:
            parameters:
              paths:
                id: true
